name: Keep Alive

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: curl -fsS https://dummy-rock.onrender.com/health/
